In [1]:
#Load the data


In [33]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd


In [34]:
x_test = pd.read_csv('mnist_test_data.csv')
y_test=pd.read_csv('mnist_test_labels.csv')
x_train=pd.read_csv('mnist_train_data.csv')
y_train=pd.read_csv('mnist_train_labels.csv')


In [4]:
#Question 1: Compute and report the prior probabilities πj for all labels. (10 marks)


In [120]:
x_test=np.array(x_test)
y_test=np.array(y_test)
x_train=np.array(x_train)
y_train=np.array(y_train)

In [6]:
labels=np.concatenate((y_train, y_test))
features=np.concatenate((x_train, x_test))
labels_features=np.concatenate((labels,features),axis=1)
labels_features.shape


(6998, 785)

In [7]:
Prior_prob1=[]
for label in labels:
    Prior_prob1.append(list(labels).count(label)/len(labels))
Prior_prob1    

[0.09674192626464705,
 0.10474421263218062,
 0.11388968276650471,
 0.0993140897399257,
 0.09959988568162333,
 0.11388968276650471,
 0.10217204915690198,
 0.11388968276650471,
 0.10474421263218062,
 0.10217204915690198,
 0.08573878250928837,
 0.10217204915690198,
 0.0993140897399257,
 0.11388968276650471,
 0.10703058016576164,
 0.09959988568162333,
 0.09145470134324092,
 0.0993140897399257,
 0.0993140897399257,
 0.10474421263218062,
 0.09674192626464705,
 0.0993140897399257,
 0.11388968276650471,
 0.11388968276650471,
 0.09959988568162333,
 0.10474421263218062,
 0.10217204915690198,
 0.09959988568162333,
 0.10703058016576164,
 0.10217204915690198,
 0.09145470134324092,
 0.0993140897399257,
 0.0993140897399257,
 0.09674192626464705,
 0.08573878250928837,
 0.0993140897399257,
 0.09674192626464705,
 0.10703058016576164,
 0.0993140897399257,
 0.11388968276650471,
 0.09145470134324092,
 0.10703058016576164,
 0.0993140897399257,
 0.10217204915690198,
 0.0993140897399257,
 0.09145470134324092,

In [8]:
alist=np.arange(0,labels_features.shape[0],1)
blist=['label']
for i in range(labels_features.shape[1]-1):
    blist.append(i)

df = pd.DataFrame(labels_features,index=alist,columns=blist) 
df


label    0    1    2    3    4    5    6    7    8  ...  774  775  776  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1       4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3       9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4       2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6       3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
7       1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
8       4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
9       3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
10      5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
11      3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
12      6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
13      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
14      7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
15      2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
16      8.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
17      6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
18      9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
19      4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
20      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
21      9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
22      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
23      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
24      2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
25      4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
26      3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
27      2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
28      7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
29      3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
6968    5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6969    4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6970    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6971    6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6972    2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6973    2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6974    3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6975    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6976    5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6977    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6978    2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6979    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6980    3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6981    8.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6982    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6983    2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6984    6.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6985    7.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6986  

In [9]:
df1=df.sort_values(by='label',ascending=True)
df1


label    0    1    2    3    4    5    6    7    8  ...  774  775  776  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2472    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6496    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2439    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2435    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2434    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2410    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2403    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2402    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2395    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2372    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2352    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2351    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2339    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2332    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6523    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2482    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2326    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2492    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6488    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2605    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2596    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2585    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2583    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2581    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2580    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2560    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2556    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2538    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2537    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
3291    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6148    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3358    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3373    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3582    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3565    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3543    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3532    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3527    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6262    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3518    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3510    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3509    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3507    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3505    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3370    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6271    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
6279    9.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3482  

In [10]:
label_uni=np.unique(labels) #remove the repeated labels
prior_prob=[]
for label in label_uni:
     prior_prob.append(list(labels).count(label)/float(len(labels)))
prior_prob


[0.09674192626464705,
 0.11388968276650471,
 0.09959988568162333,
 0.10217204915690198,
 0.10474421263218062,
 0.08573878250928837,
 0.0993140897399257,
 0.10703058016576164,
 0.09145470134324092,
 0.0993140897399257]

In [11]:
#Question 2: For each pixel Xi and label j, compute Pji = P(Xi = 1|y = j) (Use the maximum likelihood
#estimate shown in class). Use Laplacian Smoothing for computing Pji. Report the highest Pji for each label
#j. (15 marks)


In [12]:
P_ji1=[]
P_ji0=[]
for j in label_uni:
    #Laplacian Smoothing
    P_ji1.append(((df1.loc[df1['label'] == j].drop('label', 1)==1).sum(axis=1)+1)/(df1.loc[df1['label'] == j].drop('label', 1).shape[1]+2))
    P_ji0.append(((df1.loc[df1['label'] == j].drop('label', 1)==0).sum(axis=1)+1)/(df1.loc[df1['label'] == j].drop('label', 1).shape[1]+2))     
P_ji1

[0       0.160305
 2472    0.221374
 6496    0.118321
 2439    0.166667
 2435    0.105598
 2434    0.184478
 2410    0.216285
 2403    0.125954
 2402    0.171756
 2395    0.216285
 2372    0.171756
 2352    0.195929
 2351    0.137405
 2339    0.128499
 2332    0.211196
 6523    0.138677
 2482    0.209924
 2326    0.185751
 2492    0.187023
 6488    0.106870
 2605    0.115776
 2596    0.218830
 2585    0.171756
 2583    0.169211
 2581    0.215013
 2580    0.156489
 2560    0.176845
 2556    0.175573
 2538    0.229008
 2537    0.123410
           ...   
 208     0.190840
 80      0.188295
 113     0.212468
 67      0.129771
 398     0.227735
 428     0.226463
 6970    0.185751
 463     0.201018
 358     0.169211
 576     0.195929
 191     0.156489
 426     0.240458
 50      0.218830
 155     0.139949
 205     0.193384
 295     0.150127
 33      0.178117
 461     0.220102
 231     0.089059
 259     0.085242
 292     0.220102
 457     0.212468
 245     0.119593
 74      0.169211
 228     0

In [13]:
Max_p=[]
for prob in P_ji1:
    Max_p.append(max(prob))
Max_p


[0.30661577608142493,
 0.21119592875318066,
 0.2608142493638677,
 0.2837150127226463,
 0.2582697201017812,
 0.2633587786259542,
 0.2913486005089059,
 0.2608142493638677,
 0.3511450381679389,
 0.25318066157760816]

In [14]:
p_ji=[]
for j in label_uni:
    #Laplacian Smoothing
    p_ji.append((sum((df1.loc[df1['label'] == j].drop('label', 1)==1).sum(axis=1))+1)/(df1.loc[df1['label'] == j].drop('label', 1).size+2))
         
p_ji

[0.17532829662565708,
 0.07694166599983997,
 0.1490785982249062,
 0.14442470235228216,
 0.1217298851174753,
 0.12904707037810215,
 0.13800969751248895,
 0.11657851087671019,
 0.1532419752791164,
 0.12435536501481055]

In [ ]:
#Question 3: Use naive bayes (as shown in lecture slides) to classify the test data. Report the accuracy.
#(5 marks)


In [214]:
p_x0=[]
for j in label_uni:
    #Laplacian Smoothing
    p_x0.append((sum((df1.loc[df1['label'] == j].drop('label', 1)==0).sum(axis=1))+1)/(df1.loc[df1['label'] == j].drop('label', 1).size+2))
         
p_x0

[0.8246717033743429,
 0.92305833400016,
 0.8509214017750938,
 0.8555752976477178,
 0.8782701148825247,
 0.8709529296218979,
 0.8619903024875111,
 0.8834214891232898,
 0.8467580247208836,
 0.8756446349851894]

In [153]:
def CalProb(train_data,train_label): 
    num,dimsnum = train_data.shape
    labelnum = len(np.unique(train_label)) 
    pj = np.zeros((labelnum))
    pji1 = np.zeros((labelnum,dimsnum))
    for i in range(num):
        label = train_label[i][0]
        pj[label] = pj[label]+1  
        for j in range(dimsnum):
            pji1[label][j] = pji1[label][j] + train_data[i][j] 
    
    pji1 = (pji1.T + 1) / (pj + 2) 
    pj = (pj + 1) / (num + labelnum) 
    return  pj, pji1 



In [129]:
def TestProb_xi_j(xi,pji): 
    return xi * np.log(pji) + (1-xi) * np.log(1-pji)

In [154]:
p_j,p_ji1,=CalProb(x_train,y_train)


In [155]:

p_ji1.shape


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


(784, 10)

In [172]:
def classfier(test_data,test_label,pji1,pj):  
    row,column = test_data.shape
    labelnum = len(np.unique(test_label))
    acc = 0
    pred=[]
    for i in range(row):
        testdata = test_data[i,:]
        p_yj_xi = np.log(pj) 
        for j in range(labelnum): 
            for k in range(column):
                xk = testdata[k] 
                p_yj_xi[j] = p_yj_xi[j] + TestProb_xi_j(xk,pji1[j][k])
   
        p_y_xi = np.argmax(p_yj_xi)
        acc = acc + (p_y_xi == test_label[i])
        #print('real is: ',test_label[i],'  predict is: ',p_y_xi)
        pred.append(p_y_xi)
    print('Test accuracy is: ', acc/row)
    return(pred)


In [174]:
Pred=classfier(x_test,y_test,p_ji1.T,p_j)


Test accuracy is:  [0.80780781]


In [175]:
Pred

[2,
 1,
 0,
 4,
 1,
 4,
 9,
 4,
 9,
 0,
 6,
 9,
 0,
 1,
 3,
 9,
 7,
 3,
 4,
 9,
 6,
 4,
 5,
 4,
 0,
 7,
 4,
 0,
 1,
 3,
 1,
 3,
 0,
 7,
 2,
 7,
 1,
 3,
 1,
 1,
 7,
 4,
 2,
 3,
 5,
 5,
 2,
 4,
 4,
 6,
 3,
 5,
 5,
 2,
 8,
 4,
 1,
 9,
 5,
 7,
 8,
 9,
 2,
 7,
 9,
 2,
 4,
 3,
 0,
 7,
 0,
 2,
 8,
 1,
 7,
 3,
 7,
 9,
 7,
 9,
 6,
 2,
 7,
 8,
 4,
 7,
 3,
 6,
 1,
 3,
 6,
 9,
 3,
 1,
 4,
 5,
 7,
 6,
 9,
 6,
 0,
 5,
 4,
 4,
 9,
 2,
 1,
 9,
 4,
 8,
 1,
 3,
 9,
 7,
 9,
 4,
 4,
 9,
 9,
 3,
 4,
 7,
 6,
 7,
 9,
 0,
 5,
 8,
 5,
 6,
 6,
 5,
 7,
 8,
 1,
 0,
 1,
 6,
 4,
 6,
 7,
 3,
 1,
 9,
 1,
 8,
 2,
 0,
 5,
 9,
 4,
 5,
 5,
 1,
 5,
 6,
 0,
 3,
 4,
 4,
 6,
 5,
 4,
 6,
 3,
 4,
 5,
 1,
 4,
 4,
 8,
 3,
 3,
 2,
 1,
 1,
 8,
 1,
 8,
 1,
 8,
 5,
 0,
 8,
 9,
 2,
 3,
 0,
 1,
 1,
 5,
 0,
 4,
 0,
 4,
 1,
 6,
 4,
 2,
 3,
 6,
 1,
 1,
 1,
 3,
 9,
 5,
 2,
 9,
 4,
 5,
 9,
 1,
 9,
 0,
 3,
 5,
 7,
 5,
 7,
 2,
 2,
 7,
 1,
 2,
 8,
 4,
 1,
 7,
 3,
 3,
 8,
 7,
 7,
 9,
 2,
 2,
 4,
 1,
 3,
 8,
 8,
 4,
 2,
 6,
 0,
 2,
 4,
 1,
 9,


In [161]:
#Question 4: Compute the confusion matrix (as shown in the lectures) and report the top 3 pairs with most
#(absolute number) incorrect classifications. (10 marks)

In [176]:
from sklearn import metrics
from IPython.display import Image
from sklearn.metrics import confusion_matrix

In [179]:
cm = metrics.confusion_matrix(y_test, Pred)
print('The confusion matrix is: \n')
print(cm)
#Based on the matrix, we can see that the top three incorrect classificatons are (4,9),(5,3)and (8,3).


The confusion matrix is: 

[[ 74   0   0   0   0   5   2   0   4   0]
 [  0 120   0   0   0   4   1   0   1   0]
 [  1   7  88   4   0   1   2   3   8   2]
 [  0   2   1  86   1   6   3   2   3   3]
 [  1   1   1   0  83   0   2   0   1  21]
 [  3   1   1  11   2  61   2   3   2   1]
 [  3   0   4   0   3   4  73   0   0   0]
 [  0   6   2   0   3   1   0  76   3   7]
 [  0   2   2   9   4   3   1   2  61   5]
 [  0   1   0   1   4   0   0   0   3  85]]


In [335]:
#原本想用代码挑的，发现直接看更快！
Max3=[]
#for i in range(10):
    #for j in range(10):
       


In [144]:
#Question 5: Visualizing mistakes: Print two MNIST images from the test data that your classifier
#misclassified. Write both the true and predicted labels for both of these misclassified digits. (10 marks)
#Now, we will implement Gaussian Mixture Model and Linear Discriminant Analysis on the breast cancer
#data (sklearn.datasets.load breast cancer) available in sklearn.datasets. Load the data and split it into
#train-validation-test (40-20-40 split). Don’t shuffle the data, otherwise your results will be different.

In [189]:
for i in range(len(x_test)):
    if y_test[i]!= Pred[i]:
        print('real is: ',y_test[i],'  predict is: ',Pred[i])

real is:  [5]   predict is:  4
real is:  [5]   predict is:  3
real is:  [6]   predict is:  4
real is:  [4]   predict is:  0
real is:  [2]   predict is:  3
real is:  [1]   predict is:  5
real is:  [6]   predict is:  2
real is:  [0]   predict is:  8
real is:  [3]   predict is:  2
real is:  [4]   predict is:  9
real is:  [6]   predict is:  2
real is:  [9]   predict is:  8
real is:  [2]   predict is:  7
real is:  [7]   predict is:  9
real is:  [1]   predict is:  5
real is:  [9]   predict is:  4
real is:  [7]   predict is:  1
real is:  [4]   predict is:  9
real is:  [2]   predict is:  9
real is:  [5]   predict is:  3
real is:  [7]   predict is:  9
real is:  [2]   predict is:  5
real is:  [9]   predict is:  4
real is:  [5]   predict is:  3
real is:  [7]   predict is:  8
real is:  [2]   predict is:  3
real is:  [7]   predict is:  1
real is:  [5]   predict is:  3
real is:  [1]   predict is:  5
real is:  [9]   predict is:  4
real is:  [3]   predict is:  4
real is:  [3]   predict is:  1
real is:

In [275]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.mixture import GaussianMixture
from sklearn.datasets import load_breast_cancer
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd



In [276]:
data=load_breast_cancer()
len(data)
cancer_data = data['data']
cancer_target = data['target']
cancer_names = data['feature_names']
cancer_desc = data['DESCR']
X_train, X_test, y_train, y_test = train_test_split(cancer_data,cancer_target, test_size=0.4, random_state=30)
X_train, X_valid, y_train, y_valid = train_test_split(cancer_data,cancer_target,test_size=1/3,random_state=30)



In [277]:
#Question 6: Implement Gaussian Mixture model on the data as shown in class. Tune the covariance type
#parameter on the validation data. Use the selected value to compute the test accuracy. As always, train
#the model on train+validation data to compute the test accuracy. (10 mark)


In [278]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
np.isnan(y_test).any()
X_valid
cancer_names.shape

(30,)

In [323]:
colors = ['navy', 'turquoise', 'darkorange']

def make_ellipses(gmm, ax):
    for n, color in enumerate(colors):
        if gmm.covariance_type == 'full':
            covariances = gmm.covariances_[n][:1, :1]
        elif gmm.covariance_type == 'tied':
            covariances = gmm.covariances_[0:1, 0:1]
        elif gmm.covariance_type == 'diag':
            covariances = np.diag(gmm.covariances_[n][0:1,0])
        elif gmm.covariance_type == 'spherical':
            covariances = np.eye(gmm.means_.shape[1]) * gmm.covariances_[n]
        v, w = np.linalg.eigh(covariances)
        u = w[0] / np.linalg.norm(w[0])
        angle = np.arctan2(u[0], u[0])
        angle = 180 * angle / np.pi  # convert to degrees
        v = 2. * np.sqrt(2.) * np.sqrt(v)
        ell = mpl.patches.Ellipse(gmm.means_[n, :0], v[0], v[0],
                                  180 + angle, color=color)
        ell.set_alpha(0.5)
        ax.add_artist(ell)

In [295]:
clf = GaussianMixture(n_components=2, covariance_type='tied')  

clf.means_init = np.array([X_train[y_train == i].mean(axis=0)
                                for i in range(2)])
# fit
clf.fit(X_train, y_train)
# predict
pred_train = clf.predict(X_train)
pred = clf.predict(X_test)
#evaluate
print ('Train accuracy = ' + str(accuracy_score(y_train, pred_train)))
print ('Test accuracy = ' + str(accuracy_score(y_test, pred)))


Train accuracy = 0.9287598944591029
Test accuracy = 0.9298245614035088


In [ ]:
#Question 7: Apply Linear Discriminant Analysis model on the train+validation data and report the
#accuracy obtained on test data. Report the transformation matrix (w) along with the intercept. (5 mark)

In [223]:
len(cancer_names)
cancer_data.shape
cancer_target.shape

(569,)

In [232]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
# Intialize
clf = LinearDiscriminantAnalysis()
# Train
X_train=np.concatenate((X_train,X_valid))
y_train=np.concatenate((y_train,y_valid))
clf.fit(X_train, y_train)
# Test
y_pred = clf.predict(X_test)
y_train_pred = clf.predict(X_train)

# print the accuracy
print ('Training accuracy = ' + str(np.sum(y_train_pred == y_train)/len(y_train)))
print ('Test accuracy = ' + str(np.sum(y_pred == y_test)/len(y_test)))

Training accuracy = 0.9648506151142355
Test accuracy = 0.9692982456140351


In [233]:
clf = LinearDiscriminantAnalysis(n_components=2)
X_transform = clf.fit(X_train, y_train).transform(X_train)
X_test_transform = clf.transform(X_test)

In [234]:
clf.coef_

array([[ 4.11347895e+00, -8.58589944e-02, -4.48420336e-01,
        -6.00355519e-03, -1.59968634e+00,  7.97496864e+01,
        -2.64066589e+01, -4.04569128e+01, -1.94006587e+00,
        -6.28275884e-01, -8.21584783e+00,  1.27660244e-01,
         4.25383347e-01,  1.74385888e-02, -2.99470997e+02,
        -1.22595530e+00,  6.73478398e+01, -1.99617187e+02,
        -3.20609327e+01,  1.34988537e+02, -3.68679838e+00,
        -1.35232866e-01,  4.59954756e-02,  1.91009164e-02,
        -1.02539799e+01, -1.26854765e+00, -7.20029038e+00,
        -8.77031250e+00, -1.05171154e+01, -8.12881481e+01]])